version: "3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      # default
      # - .:/usr/src/app
      # for rhel
      - .:/usr/src/app:z
    tty: true
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
